Update azure-ai-agents version in requirements.txt
Fixed azure-ai-agents package version

context:

requirements.txt has incorrect package version reference. 1_1.2.0.0b2 does not exist and leads to installation errors.
https://pypi.org/project/azure-ai-agents/#history

error: "ERROR: Invalid requirement: 'azure-ai-agents>=1_1.2.0b2': Expected end or semicolon (after version specifier)
    azure-ai-agents>=1_1.2.0b2
                   ~~~^ (from line 2 of C:\Users\costaga\OneDrive - Microsoft\Documents\CSSwork\Repros\SemanticKernel\SK+MCP\azure-ai-agent-demos\mcp_local_server_agent\agent\requirements.txt)"